"""Vendor Google Fonts locally so the console makes zero external requests.

Parses the upstream CSS rather than guessing: each @font-face block keeps its
own weight range and unicode-range, so subsetting and variable axes survive the
move to local files. Only latin, latin-ext and arabic subsets are kept — the
console ships English and Arabic and nothing else, and the unused subsets are
most of the download.
"""
import hashlib
import os
import re
import urllib.request

UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')

FAMILIES = [
    'Inter:wght@400;500;600;700',
    'JetBrains+Mono:wght@400;500;700',
    'Cairo:wght@400;600;700',
]

# Subsets worth carrying. Detected from the comment Google emits above each block.
KEEP = {'latin', 'latin-ext', 'arabic'}

OUT_DIR = os.path.join('public', 'fonts')
os.makedirs(OUT_DIR, exist_ok=True)


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


blocks = []
for fam in FAMILIES:
    css = get(f'https://fonts.googleapis.com/css2?family={fam}&display=swap').decode('utf-8')
    # Google emits "/* latin */" immediately before each @font-face block.
    parts = re.split(r'/\*\s*([a-z0-9\-\[\]]+)\s*\*/', css)
    for i in range(1, len(parts) - 1, 2):
        subset, body = parts[i], parts[i + 1]
        if subset not in KEEP:
            continue
        m = re.search(r"font-family:\s*'([^']+)'", body)
        w = re.search(r'font-weight:\s*([^;]+);', body)
        u = re.search(r'url\((https://fonts\.gstatic\.com[^)]+\.woff2)\)', body)
        ur = re.search(r'unicode-range:\s*([^;]+);', body)
        if not (m and u):
            continue
        blocks.append({
            'family': m.group(1),
            'weight': (w.group(1).strip() if w else '400'),
            'url': u.group(1),
            'unicode_range': (ur.group(1).strip() if ur else None),
            'subset': subset,
        })

# Purge the earlier hash-named guesses; this pass is authoritative.
for f in os.listdir(OUT_DIR):
    if f.endswith('.woff2'):
        os.remove(os.path.join(OUT_DIR, f))

seen = {}
for b in blocks:
    h = hashlib.sha256(b['url'].encode()).hexdigest()[:8]
    slug = b['family'].lower().replace(' ', '-')
    name = f"{slug}-{b['subset']}-{b['weight'].replace(' ', '_')}-{h}.woff2"
    path = os.path.join(OUT_DIR, name)
    if b['url'] not in seen:
        open(path, 'wb').write(get(b['url']))
        seen[b['url']] = name
    b['file'] = seen[b['url']]

lines = [
    '/* ==========================================================================',
    '   SELF-HOSTED FONTS — zero external requests',
    '',
    '   These were served from fonts.googleapis.com until now, which meant every',
    '   page load of a "100% on-premises" console contacted Google and disclosed',
    '   the operator IP and usage pattern. For this product that is a sovereignty',
    '   defect, not a performance note, so the files are vendored under',
    '   public/fonts and this block replaces the remote stylesheet.',
    '',
    '   Generated by scripts/vendor-fonts (re-run to refresh). Weight ranges and',
    '   unicode-ranges are copied from upstream rather than guessed, so variable',
    '   axes and subsetting still work.',
    '   ========================================================================== */',
    '',
]
for b in blocks:
    lines.append('@font-face {')
    lines.append(f"  font-family: '{b['family']}';")
    lines.append('  font-style: normal;')
    lines.append(f"  font-weight: {b['weight']};")
    lines.append('  font-display: swap;')
    lines.append(f"  src: url('/fonts/{b['file']}') format('woff2');")
    if b['unicode_range']:
        lines.append(f"  unicode-range: {b['unicode_range']};")
    lines.append('}')
    lines.append('')

open(os.path.join('src', 'fonts.css'), 'w', encoding='utf-8').write('\n'.join(lines))

total = sum(os.path.getsize(os.path.join(OUT_DIR, f)) for f in os.listdir(OUT_DIR))
fams = sorted({b['family'] for b in blocks})
print(f'vendored {len(seen)} files, {total // 1024} KiB')
print('families:', ', '.join(fams))
print('wrote src/fonts.css with', len(blocks), '@font-face rules')
